<?php
// ─────────────────────────────────────────────────────────────
// WordPress wp-config.php — generated by setup.sh
// ─────────────────────────────────────────────────────────────

// Database
define('DB_NAME',     'MYSQL_WP_DB_PLACEHOLDER');
define('DB_USER',     'MYSQL_WP_USER_PLACEHOLDER');
define('DB_PASSWORD', 'MYSQL_WP_PASSWORD_PLACEHOLDER');
define('DB_HOST',     'mysql:3306');
define('DB_CHARSET',  'utf8mb4');
define('DB_COLLATE',  'utf8mb4_unicode_ci');

// Table prefix
$table_prefix = 'wp_';

// Security keys (generated by setup.sh via wp-cli or API)
define('AUTH_KEY',         'WP_AUTH_KEY_PLACEHOLDER');
define('SECURE_AUTH_KEY',  'WP_SECURE_AUTH_KEY_PLACEHOLDER');
define('LOGGED_IN_KEY',    'WP_LOGGED_IN_KEY_PLACEHOLDER');
define('NONCE_KEY',        'WP_NONCE_KEY_PLACEHOLDER');
define('AUTH_SALT',        'WP_AUTH_SALT_PLACEHOLDER');
define('SECURE_AUTH_SALT', 'WP_SECURE_AUTH_SALT_PLACEHOLDER');
define('LOGGED_IN_SALT',   'WP_LOGGED_IN_SALT_PLACEHOLDER');
define('NONCE_SALT',       'WP_NONCE_SALT_PLACEHOLDER');

// URL
define('WP_HOME',    'https://DOMAIN_PLACEHOLDER');
define('WP_SITEURL', 'https://DOMAIN_PLACEHOLDER');

// HTTPS
define('FORCE_SSL_ADMIN', true);
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
    $_SERVER['HTTPS'] = 'on';
}

// Performance
define('WP_MEMORY_LIMIT',     '256M');
define('WP_MAX_MEMORY_LIMIT', '512M');

// Revisions and trash
define('WP_POST_REVISIONS', 5);
define('EMPTY_TRASH_DAYS',  14);

// Automatic updates (security only)
define('WP_AUTO_UPDATE_CORE', 'minor');
define('AUTOMATIC_UPDATER_DISABLED', false);

// Debug (disabled in production)
define('WP_DEBUG',         false);
define('WP_DEBUG_LOG',     false);
define('WP_DEBUG_DISPLAY', false);
define('SCRIPT_DEBUG',     false);

// Paths
define('ABSPATH', __DIR__ . '/');
require_once ABSPATH . 'wp-settings.php';
