#!/bin/bash
# ─────────────────────────────────────────────────────────────
# docker-mailwp — Setup Wizard
# ─────────────────────────────────────────────────────────────
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

banner() {
  echo -e "${BLUE}"
  echo "  ╔══════════════════════════════════════════╗"
  echo "  ║     docker-mailwp — Setup Wizard         ║"
  echo "  ║  Mail Server + WordPress in Docker       ║"
  echo "  ╚══════════════════════════════════════════╝"
  echo -e "${NC}"
}

info()    { echo -e "${GREEN}[✓]${NC} $1"; }
warn()    { echo -e "${YELLOW}[!]${NC} $1"; }
error()   { echo -e "${RED}[✗]${NC} $1"; exit 1; }
section() { echo -e "\n${BOLD}${BLUE}── $1 ──${NC}"; }

# ─── Prerequisites ───────────────────────────────────────────
check_deps() {
  section "Checking prerequisites"
  for cmd in docker docker-compose openssl dig; do
    if command -v "$cmd" &>/dev/null; then
      info "$cmd found"
    else
      error "$cmd not found — install it before proceeding"
    fi
  done
}

# ─── Mode ────────────────────────────────────────────────────
choose_mode() {
  section "Installation mode"
  echo "  [1] Production  — VPS with public IP (Let's Encrypt)"
  echo "  [2] Development — local / LAN (self-signed certificate)"
  echo ""
  read -rp "  Choice [1/2]: " MODE_CHOICE
  case "$MODE_CHOICE" in
    1) MODE="production"; info "Mode: Production" ;;
    2) MODE="development"; warn "Mode: Development (self-signed)" ;;
    *) error "Invalid choice" ;;
  esac
}

# ─── Domain ─────────────────────────────────────────────────
ask_domain() {
  section "Domain configuration"
  read -rp "  Primary domain (e.g.: example.com): " DOMAIN
  [[ -z "$DOMAIN" ]] && error "Domain cannot be empty"

  MAIL_DOMAIN="mail.${DOMAIN}"
  info "Domain:        $DOMAIN"
  info "Mail hostname: $MAIL_DOMAIN"

  read -rp "  Administrator email: " ADMIN_EMAIL
  [[ -z "$ADMIN_EMAIL" ]] && error "Email cannot be empty"
}

# ─── Server IP ───────────────────────────────────────────────
ask_server_ip() {
  section "Server IP"
  # Auto-detect attempt
  DETECTED_IP=$(curl -s -4 https://ifconfig.me 2>/dev/null || echo "")
  if [[ -n "$DETECTED_IP" ]]; then
    read -rp "  Detected IP: ${DETECTED_IP} — confirm? [Y/n]: " CONFIRM
    if [[ "$CONFIRM" =~ ^[Nn]$ ]]; then
      read -rp "  Enter IP manually: " SERVER_IP
    else
      SERVER_IP="$DETECTED_IP"
    fi
  else
    read -rp "  Server public IP: " SERVER_IP
  fi
  [[ -z "$SERVER_IP" ]] && error "IP cannot be empty"
  info "Server IP: $SERVER_IP"
}

# ─── Passwords ─────────────────────────────────────────────
ask_passwords() {
  section "Database passwords"

  gen_pass() { openssl rand -base64 24 | tr -d '=+/' | head -c 32; }

  MYSQL_ROOT_PASSWORD=$(gen_pass)
  MYSQL_WP_PASSWORD=$(gen_pass)
  MYSQL_RC_PASSWORD=$(gen_pass)
  WP_ADMIN_PASSWORD=$(gen_pass)

  info "Passwords generated automatically (saved in .env)"
  warn "Keep the .env file in a safe place!"
}

# ─── Generate .env ──────────────────────────────────────────
generate_env() {
  section "Generating .env"
  cat > .env <<EOF
# Generated by setup.sh — $(date)
# DO NOT share this file

DOMAIN=${DOMAIN}
MAIL_DOMAIN=${MAIL_DOMAIN}
ADMIN_EMAIL=${ADMIN_EMAIL}
SERVER_IP=${SERVER_IP}
MODE=${MODE}
TZ=Europe/Paris

# MySQL
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_WP_DB=wordpress
MYSQL_WP_USER=wpuser
MYSQL_WP_PASSWORD=${MYSQL_WP_PASSWORD}
MYSQL_RC_DB=roundcube
MYSQL_RC_USER=rcuser
MYSQL_RC_PASSWORD=${MYSQL_RC_PASSWORD}

# WordPress
WP_ADMIN_USER=admin
WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
EOF
  chmod 600 .env
  info ".env created"
}

# ─── Generate DKIM key ────────────────────────────────────────
generate_dkim() {
  section "Generating DKIM key"
  mkdir -p data/opendkim/keys/${DOMAIN}
  openssl genrsa -out data/opendkim/keys/${DOMAIN}/mail.private 2048
  openssl rsa -in data/opendkim/keys/${DOMAIN}/mail.private \
              -pubout -out data/opendkim/keys/${DOMAIN}/mail.public
  chmod 600 data/opendkim/keys/${DOMAIN}/mail.private
  DKIM_PUBLIC=$(grep -v '^-' data/opendkim/keys/${DOMAIN}/mail.public | tr -d '\n')
  info "DKIM key generated"
}

# ─── Apply placeholders in config files ─────────────────────
apply_config() {
  section "Applying configurations"
  find config/ -type f | while read -r f; do
    sed -i \
      -e "s/DOMAIN_PLACEHOLDER/${DOMAIN}/g" \
      -e "s/MAIL_DOMAIN_PLACEHOLDER/${MAIL_DOMAIN}/g" \
      -e "s/SERVER_IP_PLACEHOLDER/${SERVER_IP}/g" \
      "$f"
  done
  info "Configurations applied"
}

# ─── Certificates ─────────────────────────────────────────────
setup_certs() {
  section "SSL Certificates"
  mkdir -p data/certs/live/${DOMAIN}

  if [[ "$MODE" == "development" ]]; then
    warn "Generating self-signed certificate..."
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
      -keyout data/certs/live/${DOMAIN}/privkey.pem \
      -out    data/certs/live/${DOMAIN}/fullchain.pem \
      -subj "/CN=${DOMAIN}/O=docker-mailwp/C=FR" \
      -addext "subjectAltName=DNS:${DOMAIN},DNS:*.${DOMAIN},DNS:mail.${DOMAIN},DNS:webmail.${DOMAIN}"
    info "Self-signed certificate created (valid 10 years)"
  else
    obtain_letsencrypt
  fi
}

# ─── Let's Encrypt via DNS challenge ──────────────────────────
obtain_letsencrypt() {
  # Requires acme.sh installed on the host (not in Docker)
  if ! command -v acme.sh &>/dev/null && [[ ! -f ~/.acme.sh/acme.sh ]]; then
    warn "acme.sh not found — installing automatically..."
    curl -s https://get.acme.sh | sh -s email="${ADMIN_EMAIL}"
    source ~/.bashrc 2>/dev/null || true
    ACME="$HOME/.acme.sh/acme.sh"
  else
    ACME=$(command -v acme.sh 2>/dev/null || echo "$HOME/.acme.sh/acme.sh")
  fi

  info "Requesting Let's Encrypt certificate via DNS challenge..."
  echo ""
  warn "════════════════════════════════════════════════════════"
  warn "  MANDATORY STEP — DNS CHALLENGE"
  warn "════════════════════════════════════════════════════════"
  echo ""

  # Start acme.sh in manual DNS mode
  "$ACME" --issue \
    --dns \
    -d "${DOMAIN}" \
    -d "*.${DOMAIN}" \
    --yes-I-know-dns-manual-mode-enough-go-ahead-please 2>&1 | \
    grep -E "TXT|_acme-challenge|error" || true

  echo ""
  warn "  Add the TXT record shown above in your DNS panel:"
  warn "  Name:  _acme-challenge.${DOMAIN}"
  warn "  Type:  TXT"
  warn "  Value: (the code shown above)"
  echo ""
  read -rp "  Press ENTER when you have updated DNS and waited 2-5 minutes..."

  # Verify and obtain the cert
  "$ACME" --renew \
    -d "${DOMAIN}" \
    -d "*.${DOMAIN}" \
    --yes-I-know-dns-manual-mode-enough-go-ahead-please \
    --fullchain-file "data/certs/live/${DOMAIN}/fullchain.pem" \
    --key-file       "data/certs/live/${DOMAIN}/privkey.pem"

  info "Let's Encrypt certificate obtained"
  warn "RENEWAL: acme.sh --renew -d ${DOMAIN} (every 60 days)"
  warn "Add to cron: 0 3 * * * ~/.acme.sh/acme.sh --cron"
}

# ─── Generate wp-config.php ───────────────────────────────────
generate_wp_config() {
  section "WordPress configuration"
  mkdir -p data/www/wordpress

  # WP security keys via official API
  WP_KEYS=$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ 2>/dev/null || echo "")

  cp config/wordpress/wp-config-template.php data/www/wordpress/wp-config.php

  sed -i \
    -e "s/MYSQL_WP_DB_PLACEHOLDER/${MYSQL_WP_DB:-wordpress}/g" \
    -e "s/MYSQL_WP_USER_PLACEHOLDER/${MYSQL_WP_USER:-wpuser}/g" \
    -e "s/MYSQL_WP_PASSWORD_PLACEHOLDER/${MYSQL_WP_PASSWORD}/g" \
    -e "s/DOMAIN_PLACEHOLDER/${DOMAIN}/g" \
    data/www/wordpress/wp-config.php

  if [[ -n "$WP_KEYS" ]]; then
    # Replace placeholders with real keys
    python3 -c "
import sys, re
keys = open('/dev/stdin').read()
conf = open('data/www/wordpress/wp-config.php').read()
# extract defines from API response
for line in keys.strip().split('\n'):
    m = re.match(r\"define\('([^']+)',\s*'([^']*)'\);\", line)
    if m:
        placeholder = m.group(1).replace('_','-').upper() + '-PLACEHOLDER'
        conf = conf.replace('WP_' + m.group(1) + '_PLACEHOLDER', m.group(2))
open('data/www/wordpress/wp-config.php','w').write(conf)
" <<< "$WP_KEYS" 2>/dev/null || warn "WP keys: using placeholders (edit wp-config.php manually)"
  fi

  info "wp-config.php generated"
}

# ─── Generate Roundcube config ────────────────────────────────
generate_roundcube_config() {
  section "Roundcube configuration"
  mkdir -p data/www/roundcube/config

  DES_KEY=$(openssl rand -base64 18 | head -c 24)

  sed \
    -e "s/MYSQL_RC_USER_PLACEHOLDER/${MYSQL_RC_USER:-rcuser}/g" \
    -e "s/MYSQL_RC_PASSWORD_PLACEHOLDER/${MYSQL_RC_PASSWORD}/g" \
    -e "s/MYSQL_RC_DB_PLACEHOLDER/${MYSQL_RC_DB:-roundcube}/g" \
    -e "s/DOMAIN_PLACEHOLDER/${DOMAIN}/g" \
    -e "s/ROUNDCUBE_DES_KEY_PLACEHOLDER/${DES_KEY}/g" \
    config/roundcube/config.inc.php > data/www/roundcube/config/config.inc.php

  info "Roundcube config generated"
}

# ─── Create MySQL init SQL ────────────────────────────────────
generate_mysql_init() {
  section "MySQL init script"
  cat > scripts/mysql-init.sql <<EOF
CREATE DATABASE IF NOT EXISTS \`${MYSQL_WP_DB:-wordpress}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${MYSQL_RC_DB:-roundcube}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`mailserver\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${MYSQL_WP_USER:-wpuser}'@'%' IDENTIFIED BY '${MYSQL_WP_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_RC_USER:-rcuser}'@'%' IDENTIFIED BY '${MYSQL_RC_PASSWORD}';
CREATE USER IF NOT EXISTS 'mailuser'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${MYSQL_WP_DB:-wordpress}\`.* TO '${MYSQL_WP_USER:-wpuser}'@'%';
GRANT ALL PRIVILEGES ON \`${MYSQL_RC_DB:-roundcube}\`.* TO '${MYSQL_RC_USER:-rcuser}'@'%';
GRANT SELECT ON \`mailserver\`.* TO 'mailuser'@'%';

FLUSH PRIVILEGES;

USE mailserver;
CREATE TABLE IF NOT EXISTS virtual_domains (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS virtual_users (
  id INT NOT NULL AUTO_INCREMENT,
  domain_id INT NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(150) NOT NULL,
  quota INT DEFAULT 1024,
  PRIMARY KEY (id),
  FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS virtual_aliases (
  id INT NOT NULL AUTO_INCREMENT,
  domain_id INT NOT NULL,
  source VARCHAR(100) NOT NULL,
  destination VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT IGNORE INTO virtual_domains (name) VALUES ('${DOMAIN}');
EOF
  info "MySQL init script created"
}

# ─── DNS Report ────────────────────────────────────────────────
generate_dns_report() {
  section "Generating DNS report"
  bash scripts/generate-dns-report.sh \
    "$DOMAIN" "$MAIL_DOMAIN" "$SERVER_IP" "$DKIM_PUBLIC" \
    > dns-records.txt
  info "DNS report saved to dns-records.txt"
  echo ""
  warn "═══════════════════════════════════════════════════"
  warn " IMPORTANT: configure DNS records BEFORE starting"
  warn " Read the file dns-records.txt for details"
  warn "═══════════════════════════════════════════════════"
}

# ─── Start stack ───────────────────────────────────────────────
start_stack() {
  section "Starting Docker stack"
  read -rp "  Do you want to start the stack now? [Y/n]: " START
  if [[ ! "$START" =~ ^[Nn]$ ]]; then
    if [[ "$MODE" == "production" ]]; then
      read -rp "  Have you already configured all DNS records? [y/N]: " DNS_READY
      [[ ! "$DNS_READY" =~ ^[Yy]$ ]] && warn "Configure DNS first — then run: docker-compose up -d" && return
    fi
    docker-compose up -d
    info "Stack started"
    echo ""
    info "WordPress:  https://${DOMAIN}"
    info "Webmail:    https://webmail.${DOMAIN}"
    info "Rspamd UI:  http://localhost:11334"
    echo ""
    info "WordPress admin password: ${WP_ADMIN_PASSWORD}"
    warn "Also saved in .env"
  else
    info "Manual start: docker-compose up -d"
  fi
}

# ─── MAIN ─────────────────────────────────────────────────────
main() {
  banner
  check_deps
  choose_mode
  ask_domain
  ask_server_ip
  ask_passwords
  generate_env
  generate_dkim
  apply_config
  setup_certs
  generate_mysql_init
  generate_wp_config
  generate_roundcube_config
  generate_dns_report
  start_stack

  echo ""
  echo -e "${GREEN}${BOLD}Setup complete!${NC}"
  echo ""
  echo "  Next steps:"
  echo "  1. Configure DNS records (see dns-records.txt)"
  echo "  2. Verify propagation: bash verify-dns.sh"
  echo "  3. Access WordPress: https://${DOMAIN}"
  echo ""
}

main "$@"
