[Definition]
failregex = (Authentication failure|Aborted login|No auth attempts).*rip=<HOST>
            imap-login: Disconnected.*auth=failed.*rip=<HOST>
            pop3-login: Disconnected.*auth=failed.*rip=<HOST>
ignoreregex =
