[Definition]
failregex = reject: RCPT from \S+\[<HOST>\]
            SASL (LOGIN|PLAIN|DIGEST-MD5) authentication failed.*\[<HOST>\]
            lost connection after AUTH from \S+\[<HOST>\]
            disconnect from \S+\[<HOST>\] ehlo=1 auth=0/1
ignoreregex =
